version: '3.8'

services:
  app:
    image: backendimage
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/myrestapi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: affu2004
    depends_on:
      db:
        condition: service_healthy
    networks:
      - common-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0.33
    environment:	
      MYSQL_ROOT_PASSWORD: affu2004
      MYSQL_DATABASE: myrestapi
    networks:
      - common-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    image: frontendimage
    container_name: frontendProject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - common-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  common-network:
    driver: bridge
