server:
  port: 8080

logging:
  level:
    com.template.quesans: INFO
    org.springframework: WARN

tenants:
  datasources:
    tenant1:
      url: jdbc:postgresql://localhost:5433/template_prod
      username: postgres
      password: affu2004
    tenant2:
      url: jdbc:postgresql://localhost:5433/template_tenant2_prod
      username: postgres
      password: affu2004